update public.attractions c
set cover_url=d.u, cover_credit=d.a, cover_licence=d.l, cover_source=d.s
from (values
  ('ikongo','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/ikongo.jpg','Privatemajory','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Vue_sur_Ikongo.jpg'),
  ('lake-tritriva','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/lake-tritriva.jpg','Bernard Gagnon','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Lake_Tritriva_02.jpg'),
  ('parc-national-de-l-isalo-2','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/parc-national-de-l-isalo-2.jpg','Zigomar','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:IsaloRock.jpg'),
  ('isalo-national-park','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/isalo-national-park.jpg','Zigomar','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:IsaloRock.jpg'),
  ('tritriva','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/tritriva.jpg','Zodago','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Lac_Tritriva.jpg'),
  ('arboretum-d-antsokay','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/arboretum-d-antsokay.jpg','Andry Petignat','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Entr%C3%A9e_arboretum_d%27Antsokay.jpg'),
  ('parc-national-d-ankarafantsika-2','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/parc-national-d-ankarafantsika-2.jpg','Frank Vassen from Brussels, Belgium','CC BY 2.0','https://commons.wikimedia.org/wiki/File:Lake_Ravelobe,_Ankarafantsika_National_Park,_Madagascar.jpg'),
  ('ankarafantsika-national-park','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/ankarafantsika-national-park.jpg','Frank Vassen from Brussels, Belgium','CC BY 2.0','https://commons.wikimedia.org/wiki/File:Lake_Ravelobe,_Ankarafantsika_National_Park,_Madagascar.jpg'),
  ('cascade-antomboka','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/cascade-antomboka.jpg','Marco Schmidt [1]','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Waterfall_Montagne_d_Ambre_MS5563.jpg'),
  ('parc-botanique-et-zoologique-de-tsimbazaza','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/parc-botanique-et-zoologique-de-tsimbazaza.jpg','Woodlouse from Brighton, UK','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:Taro_-_Tsimbazaza_Zoo.jpg'),
  ('botanical-and-zoological-garden-of-tsimbazaza','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/botanical-and-zoological-garden-of-tsimbazaza.jpg','Woodlouse from Brighton, UK','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:Taro_-_Tsimbazaza_Zoo.jpg'),
  ('foret-des-mikea','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/foret-des-mikea.jpg','Ozanna','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:For%C3%AAt-des-Mikea.png'),
  ('lokoho-2','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/lokoho-2.jpg','Eric Mathieu','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Lokoho_01.jpg'),
  ('lemurs-park-2','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/lemurs-park-2.jpg','Fanja37','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Entr%C3%A9e_du_parc.JPG'),
  ('rova-d-ambohimanga','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/rova-d-ambohimanga.jpg','Olivier Lejade','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:Ambohimanga_14.jpg'),
  ('anja-community-reserve','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/anja-community-reserve.jpg','Antony Stanley from Gloucester, UK','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:Anja_Reserve,_Madagascar_(3953856468).jpg'),
  ('masihanaka','https://diako.fonenako.mg/uploads/pages/wikidata/attractions/masihanaka.jpg','NASA','Public domain','https://commons.wikimedia.org/wiki/File:Lagoon_Masihanaka.jpg')
) as d(sl,u,a,l,s)
where c.slug=d.sl and c.cover_url is null;

update public.places c
set cover_url=d.u, cover_credit=d.a, cover_licence=d.l, cover_source=d.s
from (values
  ('morondava','https://diako.fonenako.mg/uploads/pages/wikidata/places/morondava.jpg','Jose Antonio. The original uploader was Jose Antonio at Italian Wikipedia.','Public domain','https://commons.wikimedia.org/wiki/File:Strada_di_Morondava.jpg'),
  ('ankify','https://diako.fonenako.mg/uploads/pages/wikidata/places/ankify.jpg','Claudia Rahary Soa','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Port_ANKIFY.jpg'),
  ('amboanana-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/amboanana-2.jpg','Andriantsoa Mickael','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Amboanana.jpg'),
  ('toliara','https://diako.fonenako.mg/uploads/pages/wikidata/places/toliara.jpg','JialiangGao www.peace-on-earth.org','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:City_Centre_Toliara_2007.jpg'),
  ('morombe','https://diako.fonenako.mg/uploads/pages/wikidata/places/morombe.jpg','Hiroki Ogawa','CC BY 3.0','https://commons.wikimedia.org/wiki/File:Three_Brothers_Baobab_Andombiry_Morombe_Madagascar_-_panoramio.jpg'),
  ('andilamena','https://diako.fonenako.mg/uploads/pages/wikidata/places/andilamena.jpg','Diorit','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Andilamena_central_town.jpg'),
  ('ifanadiana','https://diako.fonenako.mg/uploads/pages/wikidata/places/ifanadiana.jpg','Privatemajory','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Pont_d%27Ifanadiana.jpg'),
  ('nosy-be','https://diako.fonenako.mg/uploads/pages/wikidata/places/nosy-be.jpg','mwanasimba from La Réunion','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:Nosy_Be_beach_(3186856441).jpg'),
  ('nosy-komba','https://diako.fonenako.mg/uploads/pages/wikidata/places/nosy-komba.jpg','Jean-Louis Vandevivère from Paris, France','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:View_of_Nosy_Komba,_Madagascar.jpg'),
  ('andranofasika-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/andranofasika-2.jpg','Frank Vassen from Brussels, Belgium','CC BY 2.0','https://commons.wikimedia.org/wiki/File:Andranofasika_market,_January_2010,_Madagascar_(4466561827).jpg'),
  ('belo-sur-mer','https://diako.fonenako.mg/uploads/pages/wikidata/places/belo-sur-mer.jpg','Terpsichores','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Rue_principale_de_Belo_sur_Mer_-_Madagascar.jpg'),
  ('tsiroanomandidy-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/tsiroanomandidy-2.jpg','Privatemajory','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Rue_principale_de_Tsiroanomandidy.jpg'),
  ('vohemar','https://diako.fonenako.mg/uploads/pages/wikidata/places/vohemar.jpg','Tonton Bernardo','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Vohemar,_port_et_plage.jpg'),
  ('antsiranana-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/antsiranana-2.jpg','HoneyGaLe','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:MSC_Longoni_port_Antsiranana.jpg'),
  ('talata-ampano','https://diako.fonenako.mg/uploads/pages/wikidata/places/talata-ampano.jpg','Smiley.toerist','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Talata-Ampano_street.jpg'),
  ('itampolo','https://diako.fonenako.mg/uploads/pages/wikidata/places/itampolo.jpg','Andry Petignat','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Itampolo.JPG'),
  ('anjozorobe','https://diako.fonenako.mg/uploads/pages/wikidata/places/anjozorobe.jpg','Geoleval','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Gare_routi%C3%A8re_d%27Anjozorobe.jpg'),
  ('manjakandriana','https://diako.fonenako.mg/uploads/pages/wikidata/places/manjakandriana.jpg','Smiley.toerist','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Station_Manjakandriana_04.JPG'),
  ('cap-diego','https://diako.fonenako.mg/uploads/pages/wikidata/places/cap-diego.jpg','Chirocca77','CC BY 4.0','https://commons.wikimedia.org/wiki/File:Port_de_Cap_Diego_-_Antsiranana_02.jpg'),
  ('andapa','https://diako.fonenako.mg/uploads/pages/wikidata/places/andapa.jpg','Blog de l''Association Humanitaire et Caritative','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Andapa.jpg'),
  ('maintirano-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/maintirano-2.jpg','Princyadolphe','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Le_port_de_Maintirano.JPG'),
  ('ihosy','https://diako.fonenako.mg/uploads/pages/wikidata/places/ihosy.jpg','Jose Antonio','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Ihosy.JPG'),
  ('ambalavao-3','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambalavao-3.jpg','JialiangGao www.peace-on-earth.org','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Town_Centre_Ambalavao_Madagascar.jpg'),
  ('daraina-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/daraina-2.jpg','Tonton Bernardo','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Daraina,_Sava.jpg'),
  ('toamasina','https://diako.fonenako.mg/uploads/pages/wikidata/places/toamasina.jpg','Hanspeter Limacher','CC BY 3.0','https://commons.wikimedia.org/wiki/File:Tamatave_-_panoramio.jpg'),
  ('marotandrano','https://diako.fonenako.mg/uploads/pages/wikidata/places/marotandrano.jpg','Bibliothèque nationale de France','Public domain','https://commons.wikimedia.org/wiki/File:Jiro_(lumi%C3%A8re)_%C3%A0_Marotandrano._Lever_du_jour_sur_un_tombeau_malgache_-_btv1b10111737m.jpg'),
  ('vatomandry','https://diako.fonenako.mg/uploads/pages/wikidata/places/vatomandry.jpg','Roberto aime davy','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Vatomandry-plage.JPG'),
  ('vangaindrano','https://diako.fonenako.mg/uploads/pages/wikidata/places/vangaindrano.jpg','Privatemajory','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Vangaindrano.jpg'),
  ('ambodifotatra','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambodifotatra.jpg','Bluerose25','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Ambodifotatra_-_Sainte_Marie.jpg'),
  ('antalaha','https://diako.fonenako.mg/uploads/pages/wikidata/places/antalaha.jpg','Hery Zo Rakotondramanana from Antananarivo, Madagascar','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:Antalahas_beach_(4932556154).jpg'),
  ('ranomafana-3','https://diako.fonenako.mg/uploads/pages/wikidata/places/ranomafana-3.jpg','Heinonlein','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Ranomafana_2015_07.JPG'),
  ('anaborano-ifasy','https://diako.fonenako.mg/uploads/pages/wikidata/places/anaborano-ifasy.jpg','Chirocca77','CC BY 4.0','https://commons.wikimedia.org/wiki/File:Pont_Ifasy_Ambilobe_01.jpg'),
  ('ambohidrabiby','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambohidrabiby.jpg','Menafotsy','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Le_village_d%27Ambatomahamanina_vu_d%27Ambohidrabiby.JPG'),
  ('ambohitrimanjaka','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambohitrimanjaka.jpg','Lemah251','CC0','https://commons.wikimedia.org/wiki/File:La_ruelle_vers_Ambohitrimanjaka.jpg'),
  ('saint-augustin','https://diako.fonenako.mg/uploads/pages/wikidata/places/saint-augustin.jpg','JM Lebigre','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:JMLEB_002_StAugustin.JPG'),
  ('foulpointe','https://diako.fonenako.mg/uploads/pages/wikidata/places/foulpointe.jpg','Souvaroff','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Foulpointe.jpg'),
  ('ranohira','https://diako.fonenako.mg/uploads/pages/wikidata/places/ranohira.jpg','Torbenbrinker','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:RanohiraGrandRueGesch%C3%A4fte.jpg'),
  ('soavinandriana-7','https://diako.fonenako.mg/uploads/pages/wikidata/places/soavinandriana-7.jpg','Fopotra','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Culture_de_ma%C3%AFs_%C3%A0_Soavinandriana_Itasy_(45178).jpg'),
  ('ambodiampana','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambodiampana.jpg','Privatemajory','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Ambodiampana_Lokoho.jpg'),
  ('sakaraha','https://diako.fonenako.mg/uploads/pages/wikidata/places/sakaraha.jpg','Bernard Gagnon','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Sakaraha.jpg'),
  ('nosy-ve','https://diako.fonenako.mg/uploads/pages/wikidata/places/nosy-ve.jpg','sussexbirder','CC BY 2.0','https://commons.wikimedia.org/wiki/File:Nosy_Ve_Island.jpg'),
  ('imerintsiatosika','https://diako.fonenako.mg/uploads/pages/wikidata/places/imerintsiatosika.jpg','Lemah251','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Sur_la_route_d%27Imerintsiatosika.jpg'),
  ('andavadoaka','https://diako.fonenako.mg/uploads/pages/wikidata/places/andavadoaka.jpg','Dennis Tang','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:Andavadoaka_09.jpg'),
  ('mantasoa','https://diako.fonenako.mg/uploads/pages/wikidata/places/mantasoa.jpg','Dalbergiaada','CC BY 4.0','https://commons.wikimedia.org/wiki/File:Village_de_Mantasoa.jpg'),
  ('brickaville','https://diako.fonenako.mg/uploads/pages/wikidata/places/brickaville.jpg','Harald Kreutzer','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Zuckerrohrfabrik_Brickaville.JPG'),
  ('ile-aux-nattes','https://diako.fonenako.mg/uploads/pages/wikidata/places/ile-aux-nattes.jpg','JialiangGao www.peace-on-earth.org','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Beach_Ile_Aux_Nattes.jpg'),
  ('ambanja','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambanja.jpg','Claudia Rahary Soa','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Place_de_l%27ind%C3%A9pendance_AMBANJA.jpg'),
  ('ambilobe','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambilobe.jpg','B. Brassoud','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Ambilobe-Mairie.JPG'),
  ('antsampanana-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/antsampanana-2.jpg','Torbenbrinker','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:AntsampananaHauptstr.Moschee.jpg'),
  ('efoetse','https://diako.fonenako.mg/uploads/pages/wikidata/places/efoetse.jpg','Frank Vassen from Brussels, Belgium','CC BY 2.0','https://commons.wikimedia.org/wiki/File:Lake_Tsimanampetsotsa,_south-western_Madagascar_(4315971898).jpg'),
  ('ambositra-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambositra-2.jpg','Antonio Canessa','CC BY 3.0','https://commons.wikimedia.org/wiki/File:Ambositra.JPG'),
  ('hell-ville','https://diako.fonenako.mg/uploads/pages/wikidata/places/hell-ville.jpg','Anai171','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Ville_de_Nosy_Be_Hell_ville,_Madagascar.jpg'),
  ('ambondromifehy','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambondromifehy.jpg','Tonton Bernardo','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Ambondromifehy,_Diana,_RN6.jpg'),
  ('ambodifototra','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambodifototra.jpg','Michipanero','CC BY 3.0','https://commons.wikimedia.org/wiki/File:Ambodifototra_pirate_cemetery_200608_hat.jpg'),
  ('joffreville','https://diako.fonenako.mg/uploads/pages/wikidata/places/joffreville.jpg','B. Brassoud alias B-noa','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Joffreville-Mairie.JPG'),
  ('berenty','https://diako.fonenako.mg/uploads/pages/wikidata/places/berenty.jpg','Maky (Alex Dunkel)','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Berenty_001.jpg'),
  ('antsirabe-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/antsirabe-2.jpg','Bernard Gagnon','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Antsirabe_-_rue_principale02.JPG'),
  ('nosy-tanikely','https://diako.fonenako.mg/uploads/pages/wikidata/places/nosy-tanikely.jpg','Susi4','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:NosyTanikely.jpg'),
  ('nosy-sakatia','https://diako.fonenako.mg/uploads/pages/wikidata/places/nosy-sakatia.jpg','Hanay','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Nosy_Sakatia_photographed_from_the_sea_(14).jpg'),
  ('dzamandzar','https://diako.fonenako.mg/uploads/pages/wikidata/places/dzamandzar.jpg','Esculapio','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Nosy-be_Dzamandzar_0013.jpg'),
  ('baie-de-sakalava','https://diako.fonenako.mg/uploads/pages/wikidata/places/baie-de-sakalava.jpg','Chirocca77','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Baie_de_Sakalava-Ramena-Madagascar_01.jpg'),
  ('ambohibao-3','https://diako.fonenako.mg/uploads/pages/wikidata/places/ambohibao-3.jpg','NY onja Christian','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Rizi%C3%A8re_Ambohibao.jpg'),
  ('imerinafovoany','https://diako.fonenako.mg/uploads/pages/wikidata/places/imerinafovoany.jpg','Aldofeno','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Imerinafovoany_Talatamaty_rn4.jpg'),
  ('bemasoandro','https://diako.fonenako.mg/uploads/pages/wikidata/places/bemasoandro.jpg','RAMIANDRISOA James Heureux','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Bemasoandro.jpg'),
  ('ankadinondry-sakay','https://diako.fonenako.mg/uploads/pages/wikidata/places/ankadinondry-sakay.jpg','Rougailsaucix','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:2009_11_25_Madagascar_Ankadinondry-Sakay.jpg'),
  ('vohidiala','https://diako.fonenako.mg/uploads/pages/wikidata/places/vohidiala.jpg','krishna naudin','CC BY-SA 2.0','https://commons.wikimedia.org/wiki/File:Premier_train_%C3%A0_la_gare_de_Vohidiala_depuis_10_ans,_lac_alaotra,_Madagascar_(25883940980).jpg'),
  ('anosy-avaratra','https://diako.fonenako.mg/uploads/pages/wikidata/places/anosy-avaratra.jpg','Raveloaritiana Mamisoa','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Hopitaly_Anosy_Avaratra.jpg'),
  ('evatra','https://diako.fonenako.mg/uploads/pages/wikidata/places/evatra.jpg','Smiley.toerist','CC BY-SA 3.0','https://commons.wikimedia.org/wiki/File:Vuurtoren_Evatra_II.jpg'),
  ('mangily','https://diako.fonenako.mg/uploads/pages/wikidata/places/mangily.jpg','Heinonlein','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Mangily_03.JPG'),
  ('ampangorina','https://diako.fonenako.mg/uploads/pages/wikidata/places/ampangorina.jpg','Chirocca77','CC0','https://commons.wikimedia.org/wiki/File:Ampangorina_Nosy_Komba_02.jpg'),
  ('amborovy-2','https://diako.fonenako.mg/uploads/pages/wikidata/places/amborovy-2.jpg','Davidredlich','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Fisherman_in_Mahajanga_(Amborovy).jpg'),
  ('scama','https://diako.fonenako.mg/uploads/pages/wikidata/places/scama.jpg','Chirocca77','CC BY-SA 4.0','https://commons.wikimedia.org/wiki/File:Le_Samaritain-Scama-Antsiranana-Madagascar_02.jpg')
) as d(sl,u,a,l,s)
where c.slug=d.sl and c.cover_url is null;